---
title: "About this site"
date: "2019-11-29"
author:
  - name: "Qiushi Yan"
    url: https://qiushi.rbind.io
    affiliation: Communication University of China
    affiliation_url: http://www.cuc.edu.cn/
bibliography: references.bib
---

Welcome! This is a site dedicated to tricks in `ggplot2`[R-ggplot2] and creating beautiful maps with R, based on my own learning experience. This site is built on top of the `distill`[@R-distill] package, more information of which can be found [here](https://rstudio.github.io/distill/)






## Acknowledgements  {.appendix}

Distill for R Markdown builds on the work of many individuals and projects. Shan Carter, Ludwig Schubert, and Christopher Olah created the Distill web framework. John MacFarlane created the Pandoc universal markup converter. Davide Cervone and Volker Sorge created the MathJax library for rendering mathematical notation on the web. Mike Bostock created the D3 library for producing dynamic, interactive data visualizations for the web. We are grateful for the spirit of generosity that moved these individuals to create high-quality open source software for the benefit of all.